#!/bin/bash

set -euo pipefail


###############################################################################
# Project paths
###############################################################################

PROJECT_DIR="/dcs04/lieber/lcolladotor/Habenula_R01_LIBD4270/Habenula_Visium/processed-data/10_HD_bin_level/LDSC"

BED_DIR="${PROJECT_DIR}/01_DAR_beds_hg19"

# Combined manifest generated by the updated R script.
#
# Required columns:
#   dar_set
#   annotation
#   bed_file
#
# dar_set should contain:
#   open
#   closed
#   all
MANIFEST="${BED_DIR}/DAR_hg19_manifest_all_sets.tsv"

# Reserved pooled background annotation generated by 01_preprocess.R
BACKGROUND_ANNOTATION="__DAR_BACKGROUND__"


###############################################################################
# Output paths
###############################################################################

OUT_DIR="${PROJECT_DIR}/02_DAR_ldscores_hg19"

TASK_FILE="${OUT_DIR}/DAR_ldscore_tasks.tsv"

SNP_LIST_DIR="${OUT_DIR}/baselineLD_snplists"


###############################################################################
# Baseline-LD reference
###############################################################################

BASELINE_PREFIX="/users/cliu3/Thesis/LDscoredata/1000G_Phase3_baselineLD_ldscores/baselineLD."


###############################################################################
# Array script
###############################################################################

SCRIPT_DIR="/dcs04/lieber/lcolladotor/Habenula_R01_LIBD4270/Habenula_Visium/code/10_HD_bin_level/LDSC"

ARRAY_SCRIPT="${SCRIPT_DIR}/02_make_annot_ldscores_array.sh"


###############################################################################
# Create output directories
###############################################################################

mkdir -p \
    "${OUT_DIR}" \
    "${OUT_DIR}/logs" \
    "${OUT_DIR}/open" \
    "${OUT_DIR}/closed" \
    "${OUT_DIR}/all" \
    "${SNP_LIST_DIR}"


###############################################################################
# Check required files
###############################################################################

if [[ ! -s "${MANIFEST}" ]]; then
    echo "ERROR: Manifest not found or empty:"
    echo "${MANIFEST}"
    exit 1
fi

if [[ ! -s "${ARRAY_SCRIPT}" ]]; then
    echo "ERROR: Array script not found:"
    echo "${ARRAY_SCRIPT}"
    exit 1
fi


###############################################################################
# Extract exact SNP set used in baseline-LD
#
# We want the custom LD-score files to contain exactly the same SNPs,
# in exactly the same order, as baselineLD.
###############################################################################

echo ""
echo "============================================================"
echo "Creating baseline-LD SNP lists"
echo "============================================================"

for chr in $(seq 1 22); do

    baseline_ldscore="${BASELINE_PREFIX}${chr}.l2.ldscore.gz"

    snplist="${SNP_LIST_DIR}/baselineLD.${chr}.snplist"


    if [[ ! -s "${baseline_ldscore}" ]]; then
        echo "ERROR: Missing baseline-LD file:"
        echo "${baseline_ldscore}"
        exit 1
    fi


    zcat "${baseline_ldscore}" |
        awk 'NR > 1 {print $2}' \
        > "${snplist}"


    if [[ ! -s "${snplist}" ]]; then
        echo "ERROR: Failed to create SNP list:"
        echo "${snplist}"
        exit 1
    fi


    echo "chr${chr}: $(wc -l < "${snplist}") baseline SNPs"

done


###############################################################################
# Construct:
#
# DAR set × cell type × chromosome
#
# task table
#
# Columns:
#
#   1 DAR_SET
#   2 ANNOTATION
#   3 BED_FILE
#   4 CHR
#
# Example:
#
# open    Astrocyte    .../open/Astrocyte.bed    1
# open    Astrocyte    .../open/Astrocyte.bed    2
# ...
# closed  Astrocyte    .../closed/Astrocyte.bed  1
# ...
# all     Astrocyte    .../all/Astrocyte.bed     1
###############################################################################

echo ""
echo "============================================================"
echo "Constructing LDSC task table"
echo "============================================================"

: > "${TASK_FILE}"


###############################################################################
# Read the relevant columns from the manifest by COLUMN NAME rather than
# hard-coded column numbers.
#
# This avoids problems if the R manifest gets additional columns later.
###############################################################################

while IFS=$'\t' read -r dar_set annotation bed_file; do

    if [[ -z "${dar_set}" || -z "${annotation}" || -z "${bed_file}" ]]; then
        continue
    fi


    ###########################################################################
    # Validate DAR set
    ###########################################################################

    case "${dar_set}" in

        open|closed|all)
            ;;

        *)
            echo "ERROR: Unexpected dar_set in manifest:"
            echo "${dar_set}"
            exit 1
            ;;
    esac


    ###########################################################################
    # Validate BED file
    ###########################################################################

    if [[ ! -s "${bed_file}" ]]; then
        echo "ERROR: BED file does not exist or is empty:"
        echo "${bed_file}"
        exit 1
    fi


    ###########################################################################
    # Create one task per chromosome
    ###########################################################################

    for chr in $(seq 1 22); do

        printf "%s\t%s\t%s\t%s\n" \
            "${dar_set}" \
            "${annotation}" \
            "${bed_file}" \
            "${chr}" \
            >> "${TASK_FILE}"

    done

done < <(

    awk -F'\t' '
    BEGIN {
        OFS = "\t"
    }

    NR == 1 {

        for (i = 1; i <= NF; i++) {
            col[$i] = i
        }

        if (!("dar_set" in col)) {
            print "ERROR: dar_set column not found in manifest" > "/dev/stderr"
            exit 1
        }

        if (!("annotation" in col)) {
            print "ERROR: annotation column not found in manifest" > "/dev/stderr"
            exit 1
        }

        if (!("bed_file" in col)) {
            print "ERROR: bed_file column not found in manifest" > "/dev/stderr"
            exit 1
        }

        next
    }

    {
        print \
            $(col["dar_set"]), \
            $(col["annotation"]), \
            $(col["bed_file"])
    }

    ' "${MANIFEST}"
)


###############################################################################
# Add pooled background LD-score tasks
#
# The background is NOT part of the ordinary cell-type manifest because it
# should never be analyzed as a biological cell type. We add it only here so
# it receives the same annotation/LD-score construction as the foregrounds.
###############################################################################

for dar_set in open closed all; do

    background_bed="${BED_DIR}/${dar_set}/${BACKGROUND_ANNOTATION}.bed"

    if [[ ! -s "${background_bed}" ]]; then
        echo "ERROR: Missing pooled background BED:"
        echo "${background_bed}"
        exit 1
    fi

    for chr in $(seq 1 22); do
        printf "%s\t%s\t%s\t%s\n" \
            "${dar_set}" \
            "${BACKGROUND_ANNOTATION}" \
            "${background_bed}" \
            "${chr}" \
            >> "${TASK_FILE}"
    done

done


###############################################################################
# Check number of tasks
###############################################################################

N_TASKS=$(wc -l < "${TASK_FILE}")

if [[ "${N_TASKS}" -eq 0 ]]; then
    echo "ERROR: No tasks were generated."
    exit 1
fi


###############################################################################
# Print task summary
###############################################################################

echo ""
echo "Task file:"
echo "${TASK_FILE}"

echo ""
echo "Number of tasks:"
echo "${N_TASKS}"


echo ""
echo "Tasks by DAR set:"

awk -F'\t' '
{
    n[$1]++
}
END {
    print "open:   " n["open"] + 0
    print "closed: " n["closed"] + 0
    print "all:    " n["all"] + 0
}
' "${TASK_FILE}"


echo ""
echo "Annotations by DAR set:"

awk -F'\t' '
{
    key = $1 SUBSEP $2
    seen[key] = 1
}
END {

    for (key in seen) {

        split(key, x, SUBSEP)

        n[x[1]]++
    }

    print "open:   " n["open"] + 0
    print "closed: " n["closed"] + 0
    print "all:    " n["all"] + 0
}
' "${TASK_FILE}"


###############################################################################
# Preview first tasks
###############################################################################

echo ""
echo "First 10 tasks:"

head "${TASK_FILE}"


###############################################################################
# Submit Slurm array
#
# Limit concurrency to 44 simultaneous tasks.
###############################################################################

echo ""
echo "============================================================"
echo "Submitting Slurm array"
echo "============================================================"


sbatch \
    --array="1-${N_TASKS}%44" \
    --export=ALL,TASK_FILE="${TASK_FILE}",OUT_DIR="${OUT_DIR}",SNP_LIST_DIR="${SNP_LIST_DIR}" \
    --output="/dcs04/lieber/lcolladotor/Habenula_R01_LIBD4270/Habenula_Visium/processed-data/10_HD_bin_level/LDSC/logs/02_DAR_ldscores_hg19_%a.out" \
    --error="/dcs04/lieber/lcolladotor/Habenula_R01_LIBD4270/Habenula_Visium/processed-data/10_HD_bin_level/LDSC/logs/02_DAR_ldscores_hg19_%a.out" \
    "${ARRAY_SCRIPT}"